name: CD

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
          description: "set the variables secrets"
          required: false
          type: string

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: CD
        run: echo "Ejecutando CD"