name: Deploy to Production

on:
  release:
    types: [released]

jobs:

  PRE-COMMIT:
    uses: ./.github/workflows/pre-commit.yml

  CI:
    uses: ./.github/workflows/CI.yml
    needs: PRE-COMMIT
    secrets: inherit

  CD-Development:
    needs: CI
    uses: ./.github/workflows/CD.yml
    with:
      ENVIRONMENT: development

  Notificacion:
    uses: ./.github/workflows/notification.yml
    needs: CD-Development
    secrets: inherit