name: Deploy to Staging

on:
  release:
    types: [prereleased]

jobs:

  PRE-COMMIT:
    uses: ./.github/workflows/pre-commit.yml

  CI:
    uses: ./.github/workflows/CI.yml
    needs: PRE-COMMIT
    secrets: inherit

  CD:
    needs: CI
    uses: ./.github/workflows/CD.yml
    with:
      ENVIRONMENT: staging

  Notificacion:
    uses: ./.github/workflows/notification.yml
    needs: CD
    secrets: inherit